uni <- read.csv("uni", header=FALSE)
end_nodes <- read.csv("end_nodes", header=FALSE)
print(mean(uni$V1))
print(mean(end_nodes$V1))
h <- hist(end_nodes$V1, breaks=seq(2,45,by=1), plot=FALSE)
h$counts=h$counts/sum(h$counts)
plot(h)
X11()
h <- hist(uni$V1, breaks=seq(2,45,by=1), plot=FALSE)
h$counts=h$counts/sum(h$counts)
plot(h)
