res <- read.csv("res", header=FALSE)
res_uni <- read.csv("res_uni", header=FALSE)
res_uni_single <- read.csv("res_uni_single", header=FALSE)
res_single <- read.csv("res_single", header=FALSE)
print(mean(res_uni_single$V1))
print(mean(res_single$V1))
print(mean(res$V1))
print(mean(res_uni$V1))
h <- hist(res$V1, breaks=seq(1512,1536,by=1), plot=FALSE)
h$counts=h$counts/sum(h$counts)
plot(h)
X11()
h <- hist(res_uni$V1, breaks=seq(1512,1536,by=1), plot=FALSE)
h$counts=h$counts/sum(h$counts)
plot(h)
