res <- read.csv("res", header=FALSE)
res_uni <- read.csv("res_uni", header=FALSE)
res_uni_single <- read.csv("res_uni_single", header=FALSE)
res_single <- read.csv("res_single", header=FALSE)
print(mean(res_uni_single$V1))
print(mean(res_single$V1))
print(mean(res$V1))
print(mean(res_uni$V1))
hist(res_uni$V1, freq=FALSE)
X11()
hist(res$V1, freq=FALSE)
